# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Distance3D
                                 A QGIS plugin
 DE: Dieses Plugin beschriftet einen Vektorlayer mit Liniengeometrie mit der dreidimensionalen Distanz basierend auf einem DEM-Layer. Bitte beachten Sie, dass das Plugin kartesische Berechnungen verwendet, sodass bei Linien, die große Entfernungen abdecken, Ungenauigkeiten auftreten können. EN: This Plugin labels a vector layer with line geometry with the three dimensional distance based on a DEM Layer. Note that the pluging uses karthesic calculation so inaccuracies may occur on lines covering large distances.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-09-13
        copyright            : (C) 2026 by michaels
        email                : michael.stoeckeler@outlook.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Distance3D class from file Distance3D.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .distance_3d import Distance3D
    return Distance3D(iface)
