# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Distance3DDockWidget
                                 A QGIS plugin
 DE: Dieses Plugin beschriftet einen Vektorlayer mit Liniengeometrie mit der dreidimensionalen Distanz basierend auf einem DEM-Layer. Bitte beachten Sie, dass das Plugin kartesische Berechnungen verwendet, sodass bei Linien, die große Entfernungen abdecken, Ungenauigkeiten auftreten können. EN: This Plugin labels a vector layer with line geometry with the three dimensional distance based on a DEM Layer. Note that the pluging uses karthesic calculation so inaccuracies may occur on lines covering large distances.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-09-13
        git sha              : $Format:%H$
        copyright            : (C) 2026 by michaels
        email                : michael.stoeckeler@outlook.de
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal

FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'distance_3d_dockwidget_base.ui'),
    from_imports=True,
    import_from='distance_3d')


class Distance3DDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(Distance3DDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
